openapi: 3.0.3
info:
  title: Scholarly Search API
  version: 1.0.0
  description: Tools to search various scholarly sites
paths:
  /search/api/arxiv:
    get:
      operationId: arxiv_retrieve
      tags:
      - arxiv
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /search/api/elsevier:
    get:
      summary: Search the Elsevier Science Direct service.
      description: Optional extended description in CommonMark or HTML.
      operationId: elsevier_retrieve
      tags:
      - elsevier
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
